# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f82c70b94a97c5de322c5e2842be9d9842ac72a666953d35b9dccdd07f5ac04522ef109664e77e773969cb403f66d073a05e0c4997c3932af539a7e6b5523d4

test:
  secret_key_base: 9d9069c289ecaa4746a0c9dbcb5145f9289db421642d6e997c0dc6c26e64048c005fe88b9263737983488f16662d7b7f4cf112b55c199265b749eedefc9c62fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
